### ISSUE TITLE
Communication between Python and HTML files

### ISSUE THREAD

**Issue by MahanBi** [IanTerzo/Neutron#4]
What is your idea for communication?
I'm interested in making this connection using the Jinja template.
A similar use in Python and page rendering using it.

**Comment by MahanBi** [comment]
pls add requirements.txt

**Comment by IanTerzo** [comment]
Right now you can run python code in an HTML file by putting it inside { }. But this is not an optimal way because it causes some compatibility issue when using styles in HTML. If have an idea feel free to implement it. Take a look at the window.display() function.

PS the requirements.txt will be added as soon as i get back home.

**Comment by IanTerzo** [comment]
> pls add requirements.txt

If you want you can add it now, Neutron only requires pywebview, beutifulsoup and keyboard, not sure about the versions tho. (Also inspect and logging but i'm pretty sure they come with Python)
