### ISSUE TITLE
Name `Neutron` is already in use?

### ISSUE THREAD

**Issue by KrazyKirby99999** [IanTerzo/Neutron#8]
A different package is already using the name neutron https://pypi.org/project/neutron/. Perhaps neutrongui, neutronview, or something else as a package name?

**Comment by IanTerzo** [comment]
I've already noticed this before. Because pypi is case sensitive i was thinking "Neutron" with a capital "N". But this may confuse people. So maybe something like NeutronPy or NeutronWeb. I am thinking about publishing to pypi as soon as i'm done with the DOM methods and the HTMLelement class. (See to-dos)

**Comment by IanTerzo** [comment]
Perhaps the name on pypi could be `Neutron-Web` but you import it as `Neutron`

**Comment by KrazyKirby99999** [comment]
#9
